name: L2 unit test

on:
  push:
    branches: [ master, main, 'sprint/**', 'release/**' ]

  pull_request:
    # By default: opened, synchronize, or reopened
    branches: [ master, main, 'sprint/**', 'release/**' ]

jobs:
  L2-unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout this repository
          echo "Checkout this repo"
        uses: actions/checkout@v3
        with:
          path: Bundlegen

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install -r Bundlegen/requirements.txt
             pip install --editable Bundlegen/

      - name: Run the unit test
        working-directory: ./Bundlegen/unit_tests/L2_testing
        run: |
            python run_L2_test.py -m "dac-image-wayland-egl-test-appmetadata" -t "rpi3_reference_vc4_dunfell_test"
